/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolessimi;

import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class arbolesS extends javax.swing.JFrame {

    Arbol Arbol_A;
    Arbol Arbol_B;
    Arbol resultado;
    Hilo can1;
    Hilo2 can2;
    int Ladot=0;
    public arbolesS() {
        initComponents();
        Arbol_A = new Arbol();
        Arbol_B = new Arbol();
        resultado = new  Arbol();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lado = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArbolA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArbolB = new javax.swing.JPanel();
        AgregaA = new javax.swing.JButton();
        AgregaB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReciA = new javax.swing.JTextField();
        ReciB = new javax.swing.JTextField();
        MuestraAr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 500));
        getContentPane().setLayout(null);

        ArbolA.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout ArbolALayout = new javax.swing.GroupLayout(ArbolA);
        ArbolA.setLayout(ArbolALayout);
        ArbolALayout.setHorizontalGroup(
            ArbolALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ArbolALayout.setVerticalGroup(
            ArbolALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ArbolA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 40, 420, 270);

        javax.swing.GroupLayout ArbolBLayout = new javax.swing.GroupLayout(ArbolB);
        ArbolB.setLayout(ArbolBLayout);
        ArbolBLayout.setHorizontalGroup(
            ArbolBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        ArbolBLayout.setVerticalGroup(
            ArbolBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(ArbolB);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 40, 420, 270);

        AgregaA.setText("Agregar A");
        AgregaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaAActionPerformed(evt);
            }
        });
        getContentPane().add(AgregaA);
        AgregaA.setBounds(190, 330, 81, 28);

        AgregaB.setText("Agregar B");
        AgregaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaBActionPerformed(evt);
            }
        });
        getContentPane().add(AgregaB);
        AgregaB.setBounds(790, 330, 82, 28);

        jLabel1.setText("A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 54, 16);

        jLabel2.setText("B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1462, 18, 36, 16);
        getContentPane().add(ReciA);
        ReciA.setBounds(120, 330, 36, 28);
        getContentPane().add(ReciB);
        ReciB.setBounds(720, 330, 33, 28);
        getContentPane().add(MuestraAr);
        MuestraAr.setBounds(480, 420, 240, 28);

        jLabel4.setText("B");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 20, 30, 16);

        jButton1.setText("El Arbol es:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 420, 120, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaAActionPerformed
        int valor = Integer.parseInt(ReciA.getText());
        Arbol_A.insertar(valor);
        can1 = new Hilo(this);
        can1.iniciar();
    }//GEN-LAST:event_AgregaAActionPerformed

    private void AgregaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaBActionPerformed
       int valor = Integer.parseInt(ReciB.getText());
        Arbol_B.insertar(valor);
        can2 = new Hilo2(this);
        can2.iniciar();
    }//GEN-LAST:event_AgregaBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tipoArbol;
        if(Arbol_A!=null && Arbol_B!=null){
            int valor =resultado.Verificcion(Arbol_A.raiz, Arbol_B.raiz);
            switch (valor){
                case 1:
                    tipoArbol="Los Arboles son iguales";
                    MuestraAr.setText(tipoArbol);
                    break;
                case 2:
                    tipoArbol="Los Arboles son Semejantes";
                    MuestraAr.setText(tipoArbol);
                    break;
                case 3:
                    tipoArbol="Los Arboles son Similares";
                    MuestraAr.setText(tipoArbol);
                    break;
                case 4:
                    tipoArbol="Los Arboles son Diferentes";
                    MuestraAr.setText(tipoArbol);
                    break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Arbol getArbol_A() {
        return Arbol_A;
    }

    public Arbol getArbol_B() {
        return Arbol_B;
    }

    public JPanel getArbolA() {
        return ArbolA;
    }

    public JPanel getArbolB() {
        return ArbolB;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arbolesS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arbolesS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arbolesS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arbolesS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arbolesS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregaA;
    private javax.swing.JButton AgregaB;
    private javax.swing.JPanel ArbolA;
    private javax.swing.JPanel ArbolB;
    public javax.swing.ButtonGroup Lado;
    private javax.swing.JTextField MuestraAr;
    private javax.swing.JTextField ReciA;
    private javax.swing.JTextField ReciB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
